[package]
name = "zapoctak-pocitace"
version = "0.1.0"
authors = ["Richard Ivanek <richard.ivanek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
earth-moon = []

[dependencies]
